### ISSUE TITLE
infinite bile flasks in confessors room?

### ISSUE THREAD

**Issue by ObsessiveBadguy** [BrandenEK/BlasII.Randomizer#131]
i can keep smashing flasks for days and never run out of them while in the confessors hall in the city
![Screenshot 2024-12-24 070545](https://github.com/user-attachments/assets/c37fec41-1f85-451b-a2c1-00c96f6875d5)
![Screenshot 2024-12-24 070534](https://github.com/user-attachments/assets/dfe0dbd5-6e96-411c-bc20-1c16522af724)
![Screenshot 2024-12-24 070513](https://github.com/user-attachments/assets/0454586f-10c9-4756-a693-cfaae34522df)
[Latest.log](https://github.com/user-attachments/files/18240487/Latest.log)

**Comment by BrandenEK** [comment]
This is very strange.  Not sure if it is Randomizer causing it, but thank you for reporting it.  Does it not happen in any other room?  Does it still happen after restarting the game?

**Comment by Chemigoku** [comment]
This is from the game, you can take frask with full life but the frask never get empty. This is for not abuse the time stop ability from the altapieces

**Comment by ObsessiveBadguy** [comment]
Oh wow, really? I didnt know they changed that, my mistake.
