### ISSUE TITLE
Cobijada event broke the game

### ISSUE THREAD

**Issue by Chemigoku** [BrandenEK/BlasII.Randomizer#134]
If you try to give all the tributes to the Cobijadas, they never give you an item and then, crash the game:

Last Tribute to Cobijadas: [https://www.twitch.tv/chemigoku2/clip/PiercingSlipperyBeanDatSheffy-cbbLJIK04wyBP1EO](url)
Log: 
![792d0bb4a4cbcc675e7b7738abdcc6e0](https://github.com/user-attachments/assets/808ef69c-088f-4a54-8757-ed10cfc373f0)

**Comment by BrandenEK** [comment]
Can you send the spoiler for this playthrough?  I need to see what item is at that location, although I have a feeling I know what it is...

**Comment by BrandenEK** [comment]
Or the savefile preferably

**Comment by Chemigoku** [comment]
Sorry, I totally forgot to save the savefiles D: but I think that I found a similar bug in this:

Location: 
![ee0fecd8ad1f706078eb510a324ce03a](https://github.com/user-attachments/assets/9e333712-f8c6-4336-a4ba-9aebec9c8fe7)
Console: 
![037c3bbc3d2d0cb9b3ea6530d5c82a47](https://github.com/user-attachments/assets/e27adcaf-e2d8-4ed5-939e-9ec546098a3e)
Savefile: https://drive.google.com/file/d/1kvBbE5Op3EmDo-_L0fD4eRPVvsnErT_S/view?usp=sharing

**Comment by BrandenEK** [comment]
Yep, that confirms my suspicions, thank you
