### ISSUE TITLE
unable to open map at the beginning of the game and I believe I know why

### ISSUE THREAD

**Issue by ObsessiveBadguy** [BrandenEK/BlasII.Randomizer#135]
So every time I try and open the map the game basically just pauses, thankfully I can open the menu to escape a soft lock, I believe this happens because I dont get the first interaction with Anunciada after killing the first boss, where she opens your map and shows you the location of the first three bosses, pretty sure any interaction with her fixes this tho so ill let you know

**Comment by ObsessiveBadguy** [comment]
It also seems to lock you out of traveling between checkpoints too

**Comment by ObsessiveBadguy** [comment]
Oh and it prevents you from using the teleport gateways on the map past the first time apparently too

**Comment by ObsessiveBadguy** [comment]
![image](https://github.com/user-attachments/assets/40f8f899-025f-4c26-bf5d-3f6397ae8b3a)

This has sadly softlocked me tho

**Comment by ObsessiveBadguy** [comment]
[Latest.log](https://github.com/user-attachments/files/18241530/Latest.log)

**Comment by Chemigoku** [comment]
Yeah, if you enter in a TP everything works even worse

**Comment by Chemigoku** [comment]
If you try to open the Rando map in other save file, the game freeze too.

I disable the Rando Map mod for now and everything works fine, even tps

**Comment by ObsessiveBadguy** [comment]
yeah i just ran into the game freeze

**Comment by BrandenEK** [comment]
I was investigating this just now, and I can no longer replicate. It happened once, but now all my existing save files and new ones dont do it.  So I have no idea what could be causing this.

**Comment by BrandenEK** [comment]
There was a fix with Rando v2.0.0-3 that fixed an invalid location, but I believe it was still happening before that bug was introduced.  Although the problem would be different

**Comment by ObsessiveBadguy** [comment]
so currently i still get the "softlock" on the first attempt at opening the map with the current build, however im able to pause and unpause to restore movement, then afterwards the map loads just fine

**Comment by ObsessiveBadguy** [comment]
[Latest.log](https://github.com/user-attachments/files/18279000/Latest.log)
heres the log file for that scenario

**Comment by BrandenEK** [comment]
Finally fixed with the new RandoMap build.  Thank you guys!
