### ISSUE TITLE
Completed the first enemy horde room and got softlocked

### ISSUE THREAD

**Issue by ObsessiveBadguy** [BrandenEK/BlasII.Randomizer#140]
![image](https://github.com/user-attachments/assets/bbc785f6-b1fe-49f6-8d5d-617287e92ffb)

[Latest.log](https://github.com/user-attachments/files/18254272/Latest.log)

**Comment by ObsessiveBadguy** [comment]
Couldnt move or pause, controls were completely unresponsive

**Comment by ObsessiveBadguy** [comment]
was just able to replicate it too, dunno if it has to do with the item being the unfinished lullaby or not
[Latest.log](https://github.com/user-attachments/files/18254327/Latest.log)

**Comment by BrandenEK** [comment]
I fixed the crash on max level of lullaby so now it crashes on minimum level instead...
