### ISSUE TITLE
Invalid item in Devotion with item Ending A

### ISSUE THREAD

**Issue by Chemigoku** [BrandenEK/BlasII.Randomizer#145]
It's really a not big issue since you finish de game, but there's a Invalid Item there, I had the ending A item with me:

https://www.twitch.tv/chemigoku2/clip/DelightfulTsundereDootFunRun-tTYxFuD8TUoSPHDW

**Comment by Chemigoku** [comment]
[Latest.log](https://github.com/user-attachments/files/18263954/Latest.log)

**Comment by BrandenEK** [comment]
It was trying to give you the Incense of Envoys.  I dont know why they made that change...

**Comment by BrandenEK** [comment]
@Chemigoku Does it still give an invalid item if you dont have the incense?
