### ISSUE TITLE
First weapon statues don't have items

### ISSUE THREAD

**Issue by LuceScarlet** [BrandenEK/BlasII.Randomizer#15]
The first weapon statues are empty but Ruego's first one as it's the starting weapon, but the item (Z0913.l1) gave me nothing.

The second and third upgrade statues works as intended.

**Comment by BrandenEK** [comment]
This is intended, the first statue will not give you a random item, it will give you your starting weapon.  This can be changed in the "Modding/config/Randomizer.cfg" file

**Comment by LuceScarlet** [comment]
I mean the statues in Z0423 (Z0423.w0) and Z0709 (Z0709.w0), not the very first selection weapon room (Z15).
The other versions of the Randomizer let me grab their items

**Comment by BrandenEK** [comment]
Oh.  Yeah I guess I just cant read.  To fix this, I'll probably have all statues active with no pickup at any of them, even the starting weapon one.  So still the same number of locations, they are just more consistent
