### ISSUE TITLE
Insane damage with Sarmiento?

### ISSUE THREAD

**Issue by LuceScarlet** [BrandenEK/BlasII.Randomizer#16]
The normal attack with Sarmiento is just so insane.
I just got Sarmiento forcing it with the Elevated Temple Rapier statue and every hit is over 100 but electrified do 1.
After closing the game and re-opening it, the damage sets to normal.

Not sure how this works but don't mind if it's a bird the enemy or Eviterno that deals such amount of damage.

![image](https://github.com/BrandenEK/BlasII.Randomizer/assets/129603784/a0ab17ae-3d46-4e23-8fa1-68a2470aa03a)

**Comment by BrandenEK** [comment]
Very strange.  Not sure how the randomizer could be causing this issue, but I will look into it

**Comment by BrandenEK** [comment]
Actually I think you pressed Numpad8 at one point.  I forgot I still have a debug key that adds 100 to your damage whenever you press it.  LOL
