### ISSUE TITLE
Hardlock after some items

### ISSUE THREAD

**Issue by LuceScarlet** [BrandenEK/BlasII.Randomizer#28]
I got hardlocks trying different seeds after recieving an item on:

- Montañés (Sculptor)
- Yerma
- Ivy Statue

Need to keep searching for more, but other NPCs sidequests works normal

**Comment by BrandenEK** [comment]
@LuceScarlet Please provide as much information as you can with something like this, otherwise there is no way I can fix it. What exactly happened when you collected the location, did it crash or you just couldn't move. Sending the log would help. What was the seed when it happened. It is printed to the console when starting a new game, or can be found at the end of "savegame_x_modded".

**Comment by LuceScarlet** [comment]
The seed doesn't matter, but this time it was `457266`. I've rolled like 5 different seeds at this time.

This log is until the game doesn't let me move until I quit the game.
[Latest - Sculptor.log](https://github.com/BrandenEK/BlasII.Randomizer/files/12728009/Latest.-.Sculptor.log)

This is Montañes > Yerma > Ivy statue log. I solved the hardlock with S&Q mod, to have all these 3 cases in the same log
[Latest.log](https://github.com/BrandenEK/BlasII.Randomizer/files/12727979/Latest.log)

**Comment by LuceScarlet** [comment]
I've edited the .json with Marks to randomize the first part of the game but the Sculptor's inicial gift that is vanilla.
I think this should avoid tutorials for beads, figurines and all those sort of things, but I've got the very same lock.

[Latest.log](https://github.com/BrandenEK/BlasII.Randomizer/files/12728224/Latest.log)

(Changed the Randomizer data to .txt just because I can't upload the .json file)
[items.txt](https://github.com/BrandenEK/BlasII.Randomizer/files/12728288/items.txt)
[item-locations.txt](https://github.com/BrandenEK/BlasII.Randomizer/files/12728223/item-locations.txt)

**Comment by BrandenEK** [comment]
Thank you for this.  It should be fixed on the newest workflow
