### ISSUE TITLE
Bernarda's just give 1 item instead of 5

### ISSUE THREAD

**Issue by LuceScarlet** [BrandenEK/BlasII.Randomizer#29]
Bernarda's arena give the same ID `Z1501.i0` five times , so in the Randomizer you just recieve 1 item the very first time you beat the Arena instead of 5 different items

**Comment by BrandenEK** [comment]
These, along with a few other locations have duplicate ids that I haven't added special cases for yet.

**Comment by BrandenEK** [comment]
Location ids for these 5 locations have been changed to reflect the new special case for them
