### ISSUE TITLE
Item pickup text appears in Spanish even when English is the text language

### ISSUE THREAD

**Issue by BadMagic100** [BrandenEK/BlasII.Randomizer#56]
This occurred on a once after updating, and was fixed by changing the text language away from English and back.

**Comment by BrandenEK** [comment]
@BadMagic100  Interesting, it should localize everything to the current language on startup, at least on 1.1.0.  Are you on 1.0.5?  This only happened once correct, and now whenever you start the game it properly uses English?  If it happens again send the log.

**Comment by BadMagic100** [comment]
Yes, I was on 1.0.5. I believe before this I had last played on commit a39799156f6ae520dd31c386e398a4d6e6537f6a and whatever else was latest on the installer at the time. The issue occurred only once and does not appear to reoccur after a restart of the game

Log from when the issue occurred.
[Latest.log](https://github.com/BrandenEK/BlasII.Randomizer/files/13062177/Latest.log)

**Comment by BrandenEK** [comment]
Well hopefully this never occurs again
