### ISSUE TITLE
problem with Ivy of Ascension

### ISSUE THREAD

**Issue by Michele89** [BrandenEK/BlasII.Randomizer#88]
In my opinion there is a need for the Ivy of Ascension to be set as standard because I started two runs and I was always stuck in the same point. I remember that some time ago it was given at the beginning but not anymore

**Comment by BrandenEK** [comment]
The Ivy of Ascension is still placed as the first item.

Either check the spoiler log generated in the game's root folder or use the 'Rando Map' mod for an in-game map tracker that shows what locations are in logic.

Let me know if there are further problems.

**Comment by Michele89** [comment]
ok after 4 run now i have ivy at the start!

**Comment by BrandenEK** [comment]
That is the data file.  There should be a file called "spoiler_0.txt" in the same folder as "Blasphemous 2.exe".  Most likely you are just forgetting about a location, as wall climb is always one of the first 8 items.
